package org.rutebanken.proxynator;

import org.glassfish.jersey.server.ResourceConfig;
import org.rutebanken.proxynator.rest.ApplicationStatusResource;
import org.springframework.context.annotation.Configuration;

import javax.ws.rs.ApplicationPath;

/**
 *
 */
@Configuration
/*
EmbeddedServletContainerAutoConfigurationmatched
EmbeddedServletContainerAutoConfiguration.EmbeddedTomcatmatched
GenericCacheConfigurationmatched
GsonAutoConfigurationmatched
GsonAutoConfiguration#gsonmatched
GsonHttpMessageConvertersConfigurationmatched
HttpEncodingAutoConfigurationmatched
HttpEncodingAutoConfiguration#characterEncodingFiltermatched
HttpMessageConvertersAutoConfigurationmatched
HttpMessageConvertersAutoConfiguration#messageConvertersmatched
HttpMessageConvertersAutoConfiguration.StringHttpMessageConverterConfigurationmatched
HttpMessageConvertersAutoConfiguration.StringHttpMessageConverterConfiguration#stringHttpMessageConvertermatched
JacksonAutoConfigurationmatched
JacksonAutoConfiguration.Jackson2ObjectMapperBuilderCustomizerConfigurationmatched
JacksonAutoConfiguration.JacksonObjectMapperBuilderConfigurationmatched
JacksonAutoConfiguration.JacksonObjectMapperBuilderConfiguration#jacksonObjectMapperBuildermatched
JacksonAutoConfiguration.JacksonObjectMapperConfigurationmatched
JacksonAutoConfiguration.JacksonObjectMapperConfiguration#jacksonObjectMappermatched
JacksonHttpMessageConvertersConfiguration.MappingJackson2HttpMessageConverterConfigurationmatched
JacksonHttpMessageConvertersConfiguration.MappingJackson2HttpMessageConverterConfiguration#mappingJackson2HttpMessageConvertermatched
JerseyAutoConfigurationmatched
JerseyAutoConfiguration#jerseyServletRegistrationmatched
JerseyAutoConfiguration#requestContextFiltermatched
JerseyAutoConfiguration.JacksonResourceConfigCustomizermatched
JmxAutoConfigurationmatched
JmxAutoConfiguration#mbeanExportermatched
JmxAutoConfiguration#mbeanServermatched
JmxAutoConfiguration#objectNamingStrategymatched
MultipartAutoConfigurationmatched
MultipartAutoConfiguration#multipartConfigElementmatched
MultipartAutoConfiguration#multipartResolvermatched
NoOpCacheConfigurationmatched
PropertyPlaceholderAutoConfiguration#propertySourcesPlaceholderConfigurermatched
RedisCacheConfigurationmatched
ServerPropertiesAutoConfigurationmatched
ServerPropertiesAutoConfiguration#serverPropertiesmatched
SimpleCacheConfigurationmatched
WebClientAutoConfiguration.RestTemplateConfigurationmatched
WebClientAutoConfiguration.RestTemplateConfiguration#restTemplateBuildermatched
WebSocketAutoConfigurationmatched
WebSocketAutoConfiguration.TomcatWebSocketConfigurationmatched
WebSocketAutoConfiguration.TomcatWebSocketConfiguration#websocketContainerCustomizermatched

 */
@ApplicationPath("/proxynator")
public class Config extends ResourceConfig {
    public Config() {
        registerEndpoints();
    }

    private void registerEndpoints() {
        register(ApplicationStatusResource.class);
    }
}
